2025-07-06 23:51:00,927 - ERROR - Ошибка при выполнении SQL: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 707, in UpdateDict
    db.execute_user_queries(CACHE, item_id, mode)
  File "D:\PROJECTS\LPTV_Dashboard\db.py", line 173, in execute_user_queries
    if os.path.isfile(path+old_name+'.png'):
                      ~~~~^~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
2025-07-06 23:51:35,715 - ERROR - Ошибка при выполнении SQL: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 707, in UpdateDict
    db.execute_user_queries(CACHE, item_id, mode)
  File "D:\PROJECTS\LPTV_Dashboard\db.py", line 174, in execute_user_queries
    if os.path.isfile(path+old_name+'.png'):
                      ~~~~^~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
2025-07-08 20:26:51,524 - ERROR - Ошибка в UpdateProjectDesk: The `html.Div` component (version 3.1.1) received an unexpected keyword argument: `visible`
Allowed arguments: accessKey, aria-*, children, className, contentEditable, data-*, dir, disable_n_clicks, draggable, hidden, id, key, lang, n_clicks, n_clicks_timestamp, role, spellCheck, style, tabIndex, title
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 70, in UpdateProjectDesk
    html.Div(['buttons'], visible=False)
  File "C:\Users\Artem\AppData\Roaming\Python\Python312\site-packages\dash\development\base_component.py", line 475, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artem\AppData\Roaming\Python\Python312\site-packages\dash\html\Div.py", line 176, in __init__
    super(Div, self).__init__(children=children, **args)
  File "C:\Users\Artem\AppData\Roaming\Python\Python312\site-packages\dash\development\base_component.py", line 174, in __init__
    raise TypeError(
TypeError: The `html.Div` component (version 3.1.1) received an unexpected keyword argument: `visible`
Allowed arguments: accessKey, aria-*, children, className, contentEditable, data-*, dir, disable_n_clicks, draggable, hidden, id, key, lang, n_clicks, n_clicks_timestamp, role, spellCheck, style, tabIndex, title
2025-07-15 15:21:28,565 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:22:36,612 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:22:55,952 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:22:56,984 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:22:58,205 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:23:07,717 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:23:09,156 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:23:27,891 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:51:48,406 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:54:49,868 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 15:59:30,603 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 16:00:30,400 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 16:01:03,176 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 16:01:17,484 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
2025-07-15 16:01:22,058 - ERROR - Ошибка в SetUser: 'AnonymousUserMixin' object has no attribute 'name'
Traceback (most recent call last):
  File "D:\PROJECTS\LPTV_Dashboard\callback.py", line 39, in SetUser
    return user.name, 'Администратор' if user.admin == 1 else 'Сотрудник', get_user_picture(db.get_user_login(user.name))
           ^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'
